FROM docker.io/openjdk:11.0.2-jre-slim-stretch

RUN apt-get update && apt-get -y install procps && apt-get -y install vim

ADD target/financial-exchange-participants-0.0.1-SNAPSHOT.jar /
ADD RunApp.sh /

RUN chmod 775 /RunApp.sh

EXPOSE 8080/tcp

WORKDIR /
#ENTRYPOINT ["/bin/bash", "./RunApp.sh"]
CMD ["/bin/bash", "./RunApp.sh"]
