FROM docker.io/openjdk:11.0.2-jre-slim-stretch

RUN apt-get update && apt-get -y install procps && apt-get -y install vim

ADD target/financial-exchange-orderbooks-0.0.1-SNAPSHOT.jar /

ENV SERVICE_PORT 8080
ENV REMMOTE_SERVICES_BASE_URL http://localhost

EXPOSE 8080/tcp

WORKDIR /
ENTRYPOINT cd / && \
   java -jar \
   -Dserver.port=${SERVICE_PORT} \ 
   -Dremote.services.baseurl=${REMOTE_SERVICES_BASE_URL} \
   ./financial-exchange-orderbooks-0.0.1-SNAPSHOT.jar
